Big-ass refactor. For reals.

diff --git a/bandwidth b/bandwidth
--- a/bandwidth
+++ b/bandwidth
@@ -2,11 +2,12 @@
 
 TYPE=$1
 if [ "$1" != "rx" -a "$1" != "tx" ]; then
-    echo "Invalid argument: $1" 1>&2
-    echo "Must be 'tx' or 'rx'" 1>&2
-    echo "Usage: $0 (rx|tx)" 1>&2
-    exit 1
+	echo "Invalid argument: $1" 1>&2
+	echo "Must be 'tx' or 'rx'" 1>&2
+	echo "Usage: $0 (rx|tx)" 1>&2
+	exit 1
 fi
+
 
 FILE=/tmp/i3blocks_bandwidth_$TYPE
 touch $FILE
@@ -16,16 +17,17 @@ CUR=0
 
 NETDIR=/sys/class/net
 for IFACE in $(ls -1 $NETDIR); do
-    # Skip the loopback interface
-    if [ "$IFACE" == "lo" ]; then
-        continue
-    fi
-    F=$NETDIR/$IFACE/statistics/${TYPE}_bytes
-    N=$(cat $F)
-    CUR=$(expr $CUR + $N)
+	# Skip the loopback interface
+	if [ "$IFACE" == "lo" ]; then
+		continue
+	fi
+	F=$NETDIR/$IFACE/statistics/${TYPE}_bytes
+	N=$(cat $F)
+	CUR=$(expr $CUR + $N)
 done
 
-delta=$(expr $CUR - $PREV)
-echo $(expr $delta / 1000) kB/s
+delta=$(echo "$CUR - $PREV" | bc)
+echo "$(echo "$delta / 1000" | bc) kB/s"
 
+# store result
 echo $CUR > $FILE
